name: CI/CD Pipeline (Docker + Terraform)

on:
  push:
    branches: [ "main" ]

jobs:
  # ==========================================
  # ЧАСТИНА 1: Збірка Docker (З минулої ЛР)
  # ==========================================
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lab04_teampt:latest

  # ==========================================
  # ЧАСТИНА 2: Інфраструктура (Лабораторна 6)
  # ==========================================
  terraform:
    name: 'Terraform Plan & Apply'
    needs: test-and-build # Цей рядок каже: "Почекай, поки виконається test-and-build"
    runs-on: ubuntu-latest
    
    # Секрети для AWS
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-north-1'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
